import { defineConfig } from 'oxlint';

export default defineConfig({
  categories: {
    correctness: 'error',
    pedantic: 'warn',
    perf: 'warn',
    restriction: 'warn',
    style: 'warn',
    suspicious: 'warn',
  },
  env: {
    browser: true,
    es2022: true,
  },
  plugins: ['typescript', 'unicorn', 'vue'],
  rules: {
    'capitalized-comments': 'off',
    complexity: 'off',
    'func-names': 'off',
    'func-style': ['warn', 'declaration', { allowArrowFunctions: true }],
    'id-length': 'off',
    'init-declarations': 'off',
    'max-lines-per-function': 'off',
    'max-statements': 'off',
    'no-console': 'warn',
    'no-implicit-globals': 'off',
    'no-inline-comments': 'off',
    'no-magic-numbers': 'off',
    'no-nested-ternary': 'off',
    'no-ternary': 'off',
    'no-undefined': 'off',
    'no-void': 'off',
    'sort-imports': 'off',
    'sort-keys': 'off',
    'require-await': 'off',
    'typescript/explicit-function-return-type': 'off',
    'typescript/explicit-module-boundary-types': 'off',
    'typescript/no-non-null-assertion': 'off',
    'typescript/no-unsafe-type-assertion': 'off',
    'typescript/prefer-nullish-coalescing': 'off',
    'typescript/prefer-readonly-parameter-types': 'off',
    'typescript/strict-boolean-expressions': 'off',
    'unicorn/filename-case': 'off',
    'unicorn/max-nested-calls': 'off',
    'unicorn/prefer-global-this': 'off',
    'vue/max-props': 'off',
  },
});
